-- MySQL Script generated by MySQL Workbench
-- Tue Sep 12 17:02:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Makaia_Jardineria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Makaia_Jardineria` ;

-- -----------------------------------------------------
-- Schema Makaia_Jardineria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Makaia_Jardineria` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema makaia_jardineria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `makaia_jardineria` ;

-- -----------------------------------------------------
-- Schema makaia_jardineria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `makaia_jardineria` DEFAULT CHARACTER SET utf8mb3 ;
SHOW WARNINGS;
USE `Makaia_Jardineria` ;

-- -----------------------------------------------------
-- Table `Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Clientes` (
  `codigo_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `nombre_contacto` VARCHAR(45) NOT NULL,
  `apellido_contacto` VARCHAR(45) NOT NULL,
  `teléfono` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Detalle_de_Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Detalle_de_Pedidos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Detalle_de_Pedidos` (
  `codigo_pedido` INT NOT NULL AUTO_INCREMENT,
  `codigo_producto` INT NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `precio_por_unidad` DECIMAL NOT NULL,
  `Clientes_codigo_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_pedido`, `Clientes_codigo_cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Direccion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `direccion1` VARCHAR(45) NOT NULL,
  `direccion2` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `Clientes_codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`id_direccion`, `Clientes_codigo_cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleados` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Empleados` (
  `codigo_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `extension` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `Clientes_codigo_cliente` INT NOT NULL,
  `Oficinas_codigo_oficina` INT NOT NULL,
  PRIMARY KEY (`codigo_empleado`, `Clientes_codigo_cliente`, `Oficinas_codigo_oficina`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Gammas_de_Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gammas_de_Productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Gammas_de_Productos` (
  `codigo_gama` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `Productos_codigo_producto` INT NOT NULL,
  PRIMARY KEY (`codigo_gama`, `Productos_codigo_producto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficinas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficinas` (
  `codigo_oficina` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `jefe_codigo_jefe` INT NOT NULL,
  PRIMARY KEY (`codigo_oficina`, `jefe_codigo_jefe`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pagos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pagos` (
  `codigo_pago` INT NOT NULL AUTO_INCREMENT,
  `forma_pago` VARCHAR(45) NOT NULL,
  `id_transacción` VARCHAR(45) NOT NULL,
  `fecha_pago` DATE NOT NULL,
  `total_pago` DECIMAL NULL,
  `Clientes_codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`codigo_pago`, `Clientes_codigo_cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pedidos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pedidos` (
  `codigo_pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATE NOT NULL,
  `fecha_esperada` DATE NOT NULL,
  `fecha_entrega` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `comentarios` TEXT NULL,
  `Clientes_codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`codigo_pedido`, `Clientes_codigo_cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Productos` (
  `codigo_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `gama` VARCHAR(45) NOT NULL,
  `dimensiones` VARCHAR(45) NOT NULL,
  `proveedor` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  `cantidad_en_stock` INT NOT NULL,
  `precio_venta` DECIMAL NOT NULL,
  `precio_proveedor` DECIMAL NOT NULL,
  `Detalle_de_Pedidos_codigo_pedido` INT NOT NULL,
  `Detalle_de_Pedidos_Clientes_codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`codigo_producto`, `Detalle_de_Pedidos_codigo_pedido`, `Detalle_de_Pedidos_Clientes_codigo_cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jefe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jefe` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jefe` (
  `codigo_jefe` INT NOT NULL AUTO_INCREMENT,
  `codigo_oficina` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido1` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_jefe`))
ENGINE = InnoDB;

SHOW WARNINGS;
USE `makaia_jardineria` ;

-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `clientes` (
  `codigo_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `nombre_contacto` VARCHAR(45) NOT NULL,
  `apellido_contacto` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `detalle_de_pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detalle_de_pedidos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `detalle_de_pedidos` (
  `codigo_pedido` INT NOT NULL AUTO_INCREMENT,
  `codigo_producto` INT NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `precio_por_unidad` DECIMAL(10,2) NOT NULL,
  `Clientes_codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`codigo_pedido`, `Clientes_codigo_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `direccion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `direccion1` VARCHAR(45) NOT NULL,
  `direccion2` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `Clientes_codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`id_direccion`, `Clientes_codigo_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleados` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `empleados` (
  `codigo_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `extension` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `Clientes_codigo_cliente` INT NOT NULL,
  `Oficinas_codigo_oficina` INT NOT NULL,
  PRIMARY KEY (`codigo_empleado`, `Clientes_codigo_cliente`, `Oficinas_codigo_oficina`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `gammas_de_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gammas_de_productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `gammas_de_productos` (
  `codigo_gama` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `Productos_codigo_producto` INT NOT NULL,
  PRIMARY KEY (`codigo_gama`, `Productos_codigo_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jefe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jefe` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jefe` (
  `codigo_jefe` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido1` VARCHAR(45) NULL DEFAULT NULL,
  `apellido2` VARCHAR(45) NULL DEFAULT NULL,
  `codigo_oficina` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_jefe`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `oficinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficinas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `oficinas` (
  `codigo_oficina` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `jefe_codigo_jefe` INT NOT NULL,
  PRIMARY KEY (`codigo_oficina`, `jefe_codigo_jefe`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pagos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pagos` (
  `codigo_pago` INT NOT NULL AUTO_INCREMENT,
  `forma_pago` VARCHAR(45) NOT NULL,
  `id_transaccion` VARCHAR(45) NOT NULL,
  `fecha_pago` DATE NOT NULL,
  `total_pago` DECIMAL(10,2) NULL DEFAULT NULL,
  `Clientes_codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`codigo_pago`, `Clientes_codigo_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedidos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pedidos` (
  `codigo_pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATE NOT NULL,
  `fecha_esperada` DATE NOT NULL,
  `fecha_entrega` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `comentarios` TEXT NULL DEFAULT NULL,
  `Clientes_codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`codigo_pedido`, `Clientes_codigo_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `productos` (
  `codigo_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `gama` VARCHAR(45) NOT NULL,
  `dimensiones` VARCHAR(45) NOT NULL,
  `proveedor` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `cantidad_en_stock` INT NOT NULL,
  `precio_venta` DECIMAL(10,2) NOT NULL,
  `precio_proveedor` DECIMAL(10,2) NOT NULL,
  `Detalle_de_Pedidos_codigo_pedido` INT NOT NULL,
  `Detalle_de_Pedidos_Clientes_codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`codigo_producto`, `Detalle_de_Pedidos_codigo_pedido`, `Detalle_de_Pedidos_Clientes_codigo_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;


SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
